"""add agent api credentials

Revision ID: 018454b0573c
Revises: 6b2fc7adc1a5
Create Date: 2026-09-26 23:46:12.598446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018454b0573c'
down_revision: Union[str, Sequence[str], None] = '6b2fc7adc1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.add_column('agents', sa.Column('api_key_prefix', sa.String(length=20), nullable=True))
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('agents', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('agents', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('agents', 'api_key_prefix')
    op.drop_column('agents', 'api_key_hash')
    # ### end Alembic commands ###
