"""add run lifecycle completion

Revision ID: 06b709338611
Revises: 381498d03232
Create Date: 2026-09-29 19:15:14.145997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b709338611'
down_revision: Union[str, Sequence[str], None] = '381498d03232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.alter_column('runs', 'status',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('runs', 'completed_at')
    # ### end Alembic commands ###
