"""add security audit events

Revision ID: 381498d03232
Revises: 018454b0573c
Create Date: 2026-09-29 18:58:31.283895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381498d03232'
down_revision: Union[str, Sequence[str], None] = '018454b0573c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_events_agent_id'), 'security_audit_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_created_at'), 'security_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_audit_events_event_type'), 'security_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_events_severity'), 'security_audit_events', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_events_severity'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_event_type'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_created_at'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_agent_id'), table_name='security_audit_events')
    op.drop_table('security_audit_events')
    # ### end Alembic commands ###
